### ISSUE TITLE
重构HSA_BLSTM

### ISSUE THREAD

**Issue by youran521** [RMSnow/WWW2021#10]
打扰您了，请问重构HSA_BLSTM的时候，对content和comment是如何处理的？即如何获得con_embedding_matrix和com_embedding_matrix，另外con_steps和com_steps这个是具体设置的值还是通过计算得到的呢？谢谢您。

**Comment by RMSnow** [comment]
1. embedding_matrix的获取方式，和BiGRU中的embedding_matrix相似。
2. con_steps和com_steps相当于输入的最大序列长度，是一个超参数。比如可以设置为100/150/200等，这取决于文本数据本身的长度分布。

**Comment by youran521** [comment]
十分感谢您的回复。

**Comment by youran521** [comment]
十分感谢您的回复。代码中的BiGRU，Concat后，利用MLP了吗？谢谢？

**Comment by RMSnow** [comment]
利用了，可参见[此处](https://github.com/RMSnow/WWW2021/blob/5fe433144865e5918ae49de1855931b97d13327e/code/model/BiGRU.py#L57)的代码。

**Comment by youran521** [comment]
非常感谢您的回复。

**Comment by gmyfreedom** [comment]
前辈您好，打扰您了，在HSA-BLSTM程序中，comment部分对应的输入self.sub_event_num, self.post_num两个参数，分别代表什么呢？一篇news对应的comments的数量需要统一约束吗？

**Comment by gmyfreedom** [comment]
前辈您好，打扰您了，在HSA-BLSTM程序中，comment部分对应的输入self.sub_event_num, self.post_num两个参数，分别代表什么呢？一篇news对应的comments的数量需要统一约束吗？

**Comment by gmyfreedom** [comment]
> 

翻阅了原文，其中有对参数作解释，程序调试通了。感谢前辈分享代码。

**Comment by gmyfreedom** [comment]
> 前辈您好，打扰您了，在HSA-BLSTM程序中，comment部分对应的输入self.sub_event_num, self.post_num两个参数，分别代表什么呢？一篇news对应的comments的数量需要统一约束吗？

翻阅了原文，其中有对参数作解释，程序调试通了。感谢前辈分享代码。
