### ISSUE TITLE
BERT-Dual Emotion Features

### ISSUE THREAD

**Issue by isspek** [RMSnow/WWW2021#11]
Hi @RMSnow,

Thanks for this research. I would like to use dual emotion features with BERT. But I couldn't understand which script at the repository, run BERT implementation.

Could you help me please?

Thanks, 
Ipek

**Comment by RMSnow** [comment]
Hi Ipek, thanks for your interest. I am sorry but there is no implementation for BERT. I suggest you extract the dual emotion features by our provided code, and then adopt them as an additional feature set in your custom model.

Also, you can refer to our another [repo](https://github.com/ICTMCG/News-Environment-Perception/blob/e33a1bbab7d7e6390dc87b66ddd9ad8c90a4da67/model/ModelBasedOnPattern.py#L63), where we implement a PyTorch-version BERT-Emo model. I hope it can help you.
