### ISSUE TITLE
请求预处理过程的程序

### ISSUE THREAD

**Issue by WangGeStu** [RMSnow/WWW2021#5]
作者你好，
很荣幸可以拜读您的工作，我觉得这份工作对我的启发很大。
我很想在我的数据集中复现您的工作。
但是发现，经过您公开的数据集中经过您的预处理操作。
例如：
` "label": "fake",
        "content_emotions": {
            "neutral": 0.972931,
            "optimistic": 0.0044924,
            "pessimistic": 0.0225771
        },
        "comments100_emotions_mean_pooling": {
            "angry": 0.6677363333333334,
            "disgusting": 0.7911795714285714,
            "happy": 0.889665,
            "like": 0.592517,
            "neutral": 0.6185724389823528,
            "optimistic": 0.1009378232882353,
            "pessimistic": 0.2804897590882353
        },
        "comments100_emotions_max_pooling": {
            "angry": 0.805544,
            "disgusting": 0.999242,
            "happy": 0.978403,
            "like": 0.592517,
            "neutral": 1,
            "optimistic": 0.978403,
            "pessimistic": 0.999922
        }`
希望您可以公开您的预处理操作的代码，谢谢！

**Comment by RMSnow** [comment]
这些字段（除了`label`之外）均属于Emotion Category的字段，若要获取这些字段，你可以查阅[百度AI开放平台-对话情绪识别](https://ai.baidu.com/tech/nlp_apply/emotion_detection)（中文数据）或[NVIDIA-sentiment-discovery](https://github.com/NVIDIA/sentiment-discovery)（英文数据）的官方使用文档。

**Comment by WangGeStu** [comment]
感谢您的回复！
祝科研顺利！
