### ISSUE TITLE
About python input_of_semantics.py

### ISSUE THREAD

**Issue by Chenzhuomin529** [RMSnow/WWW2021#7]
Hello, when I run  input_of_semantics.py, I ran into this problem:

Traceback (most recent call last):
  File "input_of_semantics.py", line 27, in <module>
    language='Chinese', embeddings_file='../../word-embedding/sgns.weibo.bigram-char')
  File "../../word-embedding/load_embeddings.py", line 8, in load_embeddings
    with open(embeddings_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../word-embedding/sgns.weibo.bigram-char'

There is no file sgns.weibo. Bigram-char in the folder, may I ask what is wrong with me?
Thank you!

**Comment by Chenzhuomin529** [comment]
And where is the glove.twitter.27B.200d.txt?

**Comment by RMSnow** [comment]
[Readme](https://github.com/RMSnow/WWW2021/blob/master/word-embedding/readme.md) in the `word-embedding` foloder would help you. After downloading the external pretrained word embeddings (`glove.twitter.27B.200d.txt` for English, and `sgns.weibo.bigram-char` for Chinese), you need to move them into the `word-embedding` folder before running the code.

**Comment by Chenzhuomin529** [comment]
I downloaded it and ran it successfully. One question remains: where can I see the results of RMSE for Rumoureval-19?

**Comment by RMSnow** [comment]
The procedure of calculating the RMSE can be seen [here](https://github.com/RMSnow/WWW2021/blob/1aa69aff4fa6a7228841fe19654d8926e787527e/code/train/train.py#L26). I have integrated it during training, and you can find all the results in the `code/train/results` folder, where RMSE is annotated by `RMSE` key in the json files.
