### ISSUE TITLE
预处理后的数据集

### ISSUE THREAD

**Issue by youran521** [RMSnow/WWW2021#9]
您好，能提供一下预处理后的的数据集吗？另外您提供的代码是基于BIGRU的是吗？没有基于BERT和HSA-BILSTM的？？谢谢

**Comment by RMSnow** [comment]
1. 数据集采用google drive的方式共享，共享链接在[这里](https://drive.google.com/drive/folders/1pjK0BYiiJt0Ya2nRIrOLCVo-o53sYRBV?usp=sharing)，不知道你说的“预处理后的的数据集”是指的什么？
2. 是的。这个repo里主要提供了抽取Dual Emotion情感特征的代码，只提供了BiGRU作为示例。

**Comment by youran521** [comment]
谢谢您的回复。
不好意思没表达明白，我的意思是##### Step1.3: Get the `semantic features`

In this repo, we consider the semantic features as word embeddings. You need to download the preprained word embeddings ([see here](https://github.com/RMSnow/WWW2021/blob/master/word-embedding/readme.md) for more details) before running the following code:

```
cd code/preprocess
python input_of_semantics.py
```

Now, the preprocessed data are stored in `preprocess/data`.在这个步骤中，预处理后的数据存储在preprocess/data，没有这个目录，是没有提供是吗？谢谢

**Comment by youran521** [comment]
谢谢您的回复。请问现在公开的代码，如果复现，得到的结果是论文中BiGRU+Dual Emotion Features的结果吗？框架图中的MLP的作用是什么呢？谢谢

**Comment by RMSnow** [comment]
1. 你可以在[config.py](https://github.com/RMSnow/WWW2021/blob/1aa69aff4fa6a7228841fe19654d8926e787527e/code/train/config.py#L7)中设置需要训练的模型，这里提供了`MLP`（只用Dual Emotion Features）、`BiGRU`（只用BiGRU）、`EmotionEnhancedBiGRU `（BiGRU+Dual Emotion Features）三种选择。
2. MLP的作用是为了特征空间的对齐。由于Dual Emotion Features是人工提取的、抽象层次较低的统计性特征，而Fake News Detector分支则提供了Neural Network学到的、抽象层次较高的特征。把这两者concat起来之后，再使用MLP可以使它们得到更充分的交互融合。

**Comment by youran521** [comment]
非常感谢您的回复。

**Comment by youran521** [comment]
非常感谢您的回复。选择MLP进行充分的融合，您在做实验的时候是直接想到用它，还试过其他的融合方式吗？谢谢

**Comment by RMSnow** [comment]
是直接想到用它的，因为MLP是最简洁的一种融合方式。在我的实验中，其他的融合方式（例如attention）并不能显著地保证比单纯的MLP效果好（这里“效果”指的是最终的分类性能）。

**Comment by youran521** [comment]
非常感谢您的回复。

**Comment by youran521** [comment]
Emotion Category的字段，可以查阅百度AI开放平台-对话情绪识别（中文数据），但打开之后如何查阅呢？下列这些数据具体是怎么计算的呢？"content_emotions": {
            "neutral": 0.998987,
            "optimistic": 0.000120652,
            "pessimistic": 0.000892763
        },
        "comments100_emotions_mean_pooling": {
            "angry": 0.7610239999999999,
            "disgusting": 0.5909588571428571,
            "happy": 0.973989,
            "like": 0.990743,
            "neutral": 0.8379539000430526,
            "optimistic": 0.04073200154842105,
            "pessimistic": 0.12131404370526318
        },
        "comments100_emotions_max_pooling": {
            "angry": 0.999975,
            "disgusting": 0.997646,
            "happy": 0.973989,
            "like": 0.990743,
            "neutral": 0.999704,
            "optimistic": 0.990743,
            "pessimistic": 0.999991
        }谢谢

**Comment by youran521** [comment]
能提供一下中文数据预处理的程序吗？谢谢

**Comment by youran521** [comment]
您好，可以提供一下基于BERT和HSA-BILSTM的代码吗？谢谢

**Comment by RMSnow** [comment]
您好，由于时间精力所限，最近一段时间还未有空闲重构BERT和HSA-BLSTM的代码。我把原始实验时的HSA-BLSTM的模型代码上传到了[这里](https://github.com/RMSnow/WWW2021/blob/5fe433144865e5918ae49de1855931b97d13327e/code/model/HSA_BLSTM.py#L61)；关于BERT的代码，你可以参考另一个[repo](https://github.com/ICTMCG/Pref-FEND/blob/6c689bc6c35a6baa293ab54ce9483d3d1c885b9b/model/PatternBasedModels.py#L45)里的pytorch版本复现。

**Comment by youran521** [comment]
非常感谢您的回复。
